# Generated by Django 2.0.7 on 2018-07-13 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0001_squashed_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('name',), 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='hit',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='dictapp.Entry'),
        ),
    ]
