# Generated by Django 2.0.7 on 2018-07-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0002_auto_20180713_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
